---
- hosts: localhost
  become: true
  tasks:
  - name: cleanup
    command: docker rmi fleetmanapp {{ tag }}
    ignore_errors: yes
  - maven_artifact:
    group_id: com.virtualpairprogrammers
    artifact_id: fleetman
    dest: /home/ansadmin/jenkins/fleetman.jar
    version: 0.0.1-SNAPSHOT
    repository_url: http://localhost:7071/
  - name: building docker image
    command: docker build -t fleetmanapp .
    args:
      chdir: /home/ansadmin/jenkins
  - name: tag docker image
    command: "docker tag fleetmanapp {{ tag }}"
  - name: auth
    command: "docker login -u=vijayakrishnajava -p=Vijaya@012"
  - name: push the name to registry
    command: "{{item}}"
    with_items:
     - docker push {{ tag }}
  - name: cleaning
    command: "{{item}}"
    with_items:
     - rm -f *.*
     - docker system prune -f -a
    args:
      chdir: /home/ansadmin/jenkins
    ignore_errors: yes
  
        