---
- name: Create pods using deployment 
  hosts: localhost 
  become: true
  user: root
  tasks: 
  - name: create a deployment
    command: "kubectl apply -f deploy.yaml"
    args:
      chdir: /home/ansadmin/jenkins
  - name: update deployment with new pods if image updated in docker hub
    command: "kubectl rollout restart deployment.v1.apps/api-gateway"
    
